---
- name: apt update
  apt:
    update-cache: yes
  become: yes

- name: install software properties common
  apt:
    name: software-properties-common
  become: yes

- name: add repository
  apt_repository:
    repo: "ppa:ansible/ansible"
  become: yes

- name: install ansible
  apt:
    name: ansible
  become: yes
