---
- import_playbook: bootstrap.yml

- hosts: all
  tasks:
  - name: setup vim
    import_role: name=vim
  - name: install required packages
    apt:
      name: 
      - virtualenv
      - python-pip
      - lxc-dev
      - lxc-utils
      - lxc-templates
    become: yes
  - name: install required module for lxc
    pip:
      name: lxc-python2
  - name: setup lxc
    lxc_container:
      name: test
      container_log: true
      template: ubuntu
      state: started
      template_options: --release xenial
    become: yes

