---
- import_playbook: bootstrap.yml

- hosts: all
  tasks:
  - name: setup lxc
    import_role:
      name: lxc
    tags:
    - lxc

  - name: tools
    import_role:
      name: tools
    tags:
    - tools

  - name: ansible
    import_role:
      name: ansible
    tags:
    - ansible
